_target_: src.models.gem_model.BaseNet

lr: 1e-3
weight_decay: 1e-4
optimizer: "adamw"
loss_fn: "mse"

encoder:
  _target_: src.models.components.gem1.GEM1
  embed_dim: 32
  dropout: 0.1
  last_act: True
  n_layers: 3
  pool: "mean"

classifier:
  _target_: src.models.components.gem1.Classifier
  input_dim: 32
  hidden_dims: [256, 256]
  batch_norm: True
  dropout: 0.5