_target_: src.models.model.BaseNet

lr: 1e-3
weight_decay: 1e-4

net:
  _target_: src.models.components.gin.GIN
  gin_mlp_hidden_dim: 512
  gin_hidden_dim: 256
  n_fc_layers: 3
  fc_hidden_dim: 256
  fc_dropout: 0.5
