# https://wandb.ai

wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  name: ""
  group: ""
  save_dir: "${paths.output_dir}"
  offline: False
  id: null # pass correct id to resume experiment!
  anonymous: null # enable anonymous logging
  project: "samsung-ai-challenge"
  entity: "danyeong-lee"
  log_model: False # upload lightning ckpts
  prefix: "" # a string to put at the beginning of metric keys
  tags: []
  job_type: ""
