defaults:
  - model_checkpoint.yaml
  - early_stopping.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/ckpts
  filename: "best"
  monitor: "val/rmse"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False


early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: "val/rmse" 
  patience: 10 
  mode: "min"

model_summary:
  max_depth: -1
